
CREATE TABLE REFERENCE_TAG (
    -- THE APRIL TAG ID
    TAG_ID INT PRIMARY KEY,
    -- HOW BIG THE APRIL TAG IS
    SCALE_M DECIMAL,
    -- THE OFFSET OF HEIGHT BETWEEN THE PLANT AND THE APRIL TAG BOTTOM
    BIAS_M DECIMAL,
    -- REQUEST TYPE OF TAG, HEIGHT, OR AREA
    REQUEST_TYPE TEXT NOT NULL,

    CAMERA_ID NOT NULL,
        REFERENCES CAMERA(CAMERA_ID)

    -- CONSTRAINTS TO MAKE SURE THAT THE SCALE IS NOT NEGATIVE
    -- AND THAT REQUEST TYPE IS VALID 
    CONSTRAINT SCALE_POSITIVE_CHECK (SCALE_M > 0)
    CONSTRAINT REQUEST_TYPE_VALID CHECK (
        REQUEST_TYPE IN (
            'HEIGHT_REQUEST',
            'AREA_REQUEST'
        )
    )
);

CREATE TABLE TAG_PLANT_BOUNDS (
    ID SERIAL PRIMARY KEY,

    TAG_ID INT NOT NULL 
        REFERENCES REFERENCE_TAG(TAG_ID)
        ON DELETE CASCADE,

    PLANT_ID INT NOT NULL
        REFERNCES PLANT(PLANT_ID)
        ON DELETE CASCADE,
    
    X_MIN_PERCENT INT NOT NULL DEFAULT 0,
    X_MAX_PERCENT INT NOT NULL DEFAULT 1
)

CREATE TABLE CAMERA (
    CAMERA_ID INT PRIMARY KEY,
    WIDTH INT NOT NULL DEFAULT 1024,
    HEIGHT INT NOT NULL DEFUALT 768,
    FOCAL_LENGTH_MM DECIMAL NOT NULL DEFAULT 3.6,
    SENSOR_HEIGHT_MM DECIMAL NOT NULL DEFAULT 2.2684,
    SENOSR_WIDTH_MM DECIMAL NOT NULL DEFAULT 3.590,
    IP_ADDRESS VARCHAR(10) NOT NULL, 
);

CREATE TABLE PLANT (
    PLANT_ID INT PRIMARY KEY
    PLANT_SPECIES REFERENCES PLANT_SPECIES(SCEINTIFIC_NAME)
)

CREATE TABLE PLANT_SPECIES (
    SCIENTIFIC_NAME PRIMARY KEY TEXT,
    COMMON_NAME TEXT,
    
    COLOR_LOWER_H INT NOT NULL,
    COLOR_LOWER_S INT NOT NULL,
    COLOR_LOWER_V INT NOT NULL,

    COLOR_UPPER_H INT NOT NULL,
    COLOR_UPPER_S INT NOT NULL,
    COLOR_UPPER_V INT NOT NULL
)

CREATE TABLE HEIGHT_LOG (
    ID SERIAL PRIMARY KEY,
    PLANT_ID REFERENCES PLANT(PLANT_ID),
    HEIGHT DECIMAL NOT NULL,
    TIMESTAMP TIMESTAMP 
)

